direction: down

toolmodel -> toolindex

toolindex -> tooldocs
 toolindex -> toolrun

 toolrun -> toolcode
 toolcode -> toolruntime

 toolindex -> toolsearch
 toolindex -> metatools-mcp
 tooldocs -> metatools-mcp
 toolrun -> metatools-mcp
 toolcode -> metatools-mcp
