#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECTS_DIR_DEFAULT="$HOME/Documents/Projects"
PROJECTS_DIR="$PROJECTS_DIR_DEFAULT"
OUTPUT="$ROOT_DIR/docs/operations/stack-changelog.md"

REPOS=(
  ai-tools-stack
  toolmodel
  toolindex
  tooldocs
  toolrun
  toolcode
  toolruntime
  toolsearch
  metatools-mcp
)

usage() {
  cat <<USAGE
Usage:
  scripts/generate-combined-changelog.sh [--projects DIR]

Options:
  --projects    Override projects dir (default: $PROJECTS_DIR_DEFAULT)
  -h, --help    Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --projects)
      PROJECTS_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

extract_latest() {
  local changelog="$1"
  awk '
    BEGIN {found=0}
    /^## / {if(found) exit; found=1}
    found {print}
  ' "$changelog"
}

latest_version_line() {
  local block="$1"
  echo "$block" | head -n1
}

echo "# Stack Changelog" > "$OUTPUT"
echo >> "$OUTPUT"
echo "Aggregated highlights from each repo’s latest release. For full history, use each repo’s CHANGELOG." >> "$OUTPUT"
echo >> "$OUTPUT"

echo "## Version matrix" >> "$OUTPUT"
if [[ -f "$ROOT_DIR/VERSIONS.md" ]]; then
  tail -n +1 "$ROOT_DIR/VERSIONS.md" | sed '1s/^## /### /' >> "$OUTPUT"
else
  echo "Version matrix not available." >> "$OUTPUT"
fi

echo >> "$OUTPUT"

for repo in "${REPOS[@]}"; do
  repo_dir="$PROJECTS_DIR/$repo"
  changelog="$repo_dir/CHANGELOG.md"
  if [[ ! -f "$changelog" ]]; then
    continue
  fi

  block="$(extract_latest "$changelog")"
  if [[ -z "$block" ]]; then
    continue
  fi

  version_line="$(latest_version_line "$block")"
  version="$(sed -n 's/^## \[\([^]]*\)\].*/\1/p' <<< "$version_line")"
  link="$(sed -n 's/^## \[\([^]]*\)\](\([^)]*\)).*/\2/p' <<< "$version_line")"

  echo "## $repo" >> "$OUTPUT"
  if [[ -n "$version" && -n "$link" ]]; then
    echo "**Latest:** [$version]($link)" >> "$OUTPUT"
  elif [[ -n "$version" ]]; then
    echo "**Latest:** $version" >> "$OUTPUT"
  fi
  echo >> "$OUTPUT"

  # Remove the first line (version header) and keep the rest.
  echo "$block" | tail -n +2 >> "$OUTPUT"
  echo >> "$OUTPUT"
  echo "[Full changelog](https://github.com/jonwraymond/$repo/blob/main/CHANGELOG.md)" >> "$OUTPUT"
  echo >> "$OUTPUT"

done

echo "Generated by scripts/generate-combined-changelog.sh" >> "$OUTPUT"
