#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECTS_DIR_DEFAULT="$HOME/Documents/Projects"
if [[ -d "$ROOT_DIR/../toolfoundation" && -d "$ROOT_DIR/../tooldiscovery" ]]; then
  PROJECTS_DIR_DEFAULT="$(cd "$ROOT_DIR/.." && pwd)"
fi
PROJECTS_DIR="$PROJECTS_DIR_DEFAULT"
OUTPUT="$ROOT_DIR/docs/operations/stack-changelog.md"

REPOS=(
  ai-tools-stack
  toolfoundation
  tooldiscovery
  toolexec
  toolcompose
  toolops
  toolprotocol
  metatools-mcp
  metatools-a2a
)

usage() {
  cat <<USAGE
Usage:
  scripts/generate-combined-changelog.sh [--projects DIR]

Options:
  --projects    Override projects dir (default: $PROJECTS_DIR_DEFAULT)
  -h, --help    Show this help
USAGE
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --projects)
      PROJECTS_DIR="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

echo "# Stack Changelog" > "$OUTPUT"
echo >> "$OUTPUT"
echo "Aggregated highlights from each repo’s latest release. For full history, use each repo’s CHANGELOG." >> "$OUTPUT"
echo >> "$OUTPUT"

echo "## Version matrix (current tags)" >> "$OUTPUT"
if [[ -f "$ROOT_DIR/VERSIONS.md" ]]; then
  tail -n +1 "$ROOT_DIR/VERSIONS.md" | sed '1s/^## /### /' >> "$OUTPUT"
else
  echo "Version matrix not available." >> "$OUTPUT"
fi

echo >> "$OUTPUT"

echo "## Repo changelogs" >> "$OUTPUT"
echo >> "$OUTPUT"
for repo in "${REPOS[@]}"; do
  echo "- [${repo}](https://github.com/jonwraymond/${repo}/blob/main/CHANGELOG.md)" >> "$OUTPUT"
done
echo >> "$OUTPUT"
echo "## Notes" >> "$OUTPUT"
echo >> "$OUTPUT"
echo "- The stack was consolidated from 13 standalone repos into 6 library repos." >> "$OUTPUT"
echo "- Legacy repo changelogs remain available in their archived repositories." >> "$OUTPUT"
echo >> "$OUTPUT"

echo "Generated by scripts/generate-combined-changelog.sh" >> "$OUTPUT"
